### ISSUE TITLE
how to make it work?

### ISSUE THREAD

**Issue by Amaren1** [ringosham/autoclicker#1]
title

**Comment by ringosham** [comment]
I have no idea what you are asking

**Comment by Amaren1** [comment]
I open exe and nothing happens

**Comment by ringosham** [comment]
I can't reproduce your issue.
Make sure you have .NET desktop runtime installed.

**Comment by Amaren1** [comment]
Could you please make a 10 seconds video of you using the clicker?  I have no clue how to use it...

**Comment by ringosham** [comment]
Huh?
It's literally press the hotkey shown in the application and it will start autoclicking.
![image](https://user-images.githubusercontent.com/7325740/133454114-65d76fd3-13e1-4841-a660-bbc11859a989.png)
This is what you should see. If you don't see a window, it's likely something went wrong with your Windows installation.
